page:
  size:
    w: 15.5
    h: 8.0
  children:
    - card:
        flex: 1
        children:
          - section:
              title: PackerMOD Settings
              children:
                - label:
                    text: "User data path: ${user_path}"
                    style: dim
                - label:
                    text: "PackerMOD version: ${version}"
                    style: dim
                - label:
                    text: "Luanti version: ${luanti_version}"
                    style: dim
                - spacer:
                    flex: 1
                - actions:
                    children:
                      - icon-button:
                          name: open_luanti_settings
                          icon: sliders
                          label: Open Luanti settings
                          variant: secondary
                          w: 4.0
                          h: 0.8
